version: "3.3"
services:
    website:
      image: nginx:1.23.1-alpine
      ports:
        - "9090:80"
      volumes:
        - "/disk1/Workspace/orchestration/docker-compose/nginx/html:/usr/share/nginx/html:ro"
        - "/disk1/Workspace/orchestration/docker-compose/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro"
      deploy:
        resources:
          limits:
            cpus: 0.50
            memory: 512M
          reservations:
            cpus: 0.25
            memory: 128M