# Run the file with sudo kubectl create -f nginx-deploy-kubernenetes.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-http-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-http-server
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-http-server
    name: nginx-http-server
spec:
  containers:
  - image: nginx
    name: nginx-http-server
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
