version: "3.3"
services:
    portainer:
      image: portainer/portainer-ce
      ports:
        - "8000:8000"
        - "9000:9000"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/disk1/Workspace/orchestration/docker-compose/portainer/portainer_data:/data portainer/portainer-ce"
      deploy:
        resources:
          limits:
            cpus: 2
            memory: 512M
          reservations:
            cpus: 2
            memory: 128M