apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
        - name: go-webserver
          image: k3d-registry.localhost:5050/go-webserver:v0.1
          ports:
            - containerPort: 9091
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
