apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-webserver
  name: go-webserver
spec:
  type: NodePort
  ports:
    - name: "go-webserver-service"
      # Port accessible inside cluster
      port: 5001
      # Port to forward to inside the pod (application exposed port)
      targetPort: 9091
      # Port accessible outside cluster
      nodePort: 30001
  selector:
    app: go-webserver