apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  type: NodePort
  ports:
    - name: "myapp-service"
      # Port accessible inside cluster
      port: 5000
      # Port to forward to inside the pod (application exposed port)
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30000
  selector:
    app: myapp